In [1]:
import pandas as pd
import numpy as np
import os

# generators

In [2]:
generators_df = pd.read_csv("etrago_test_network_1/generators.csv")
generators_df

name  bus                  carrier  p_nom  p_nom_opt
0                    0 biomass    0                  biomass    1.0        1.0
1                   10 biomass   10                  biomass   10.0       10.0
2        0 central_biomass_CHP    0      central_biomass_CHP    1.0        1.0
3       10 central_biomass_CHP   10      central_biomass_CHP   10.0       10.0
4               0 run_of_river    0             run_of_river    1.0        1.0
5              10 run_of_river   10             run_of_river   10.0       10.0
6                        0 gas    0                      gas    1.0        1.0
7                       10 gas   10                      gas   10.0       10.0
8        0 other_non_renewable    0      other_non_renewable    1.0        1.0
9       10 other_non_renewable   10      other_non_renewable   10.0       10.0
10                 0 reservoir    0                reservoir    1.0        1.0
11                10 reservoir   10                reservoir   10.0       10.0
12                   0 solar_0    0                    solar    1.0        1.0
13                   0 solar_1    0                    solar   10.0       10.0
14                  10 solar_0   10                    solar    1.0        1.0
15                  10 solar_1   10                    solar   10.0       10.0
16           0 solar_rooftop_0    0            solar_rooftop    1.0        1.0
17           0 solar_rooftop_1    0            solar_rooftop   10.0       10.0
18          10 solar_rooftop_0   10            solar_rooftop    1.0        1.0
19          10 solar_rooftop_1   10            solar_rooftop   10.0       10.0
20            0 wind_onshore_0    0             wind_onshore    1.0        1.0
21            0 wind_onshore_1    0             wind_onshore   10.0       10.0
22           10 wind_onshore_0   10             wind_onshore    1.0        1.0
23           10 wind_onshore_1   10             wind_onshore   10.0       10.0
24   4 solar_thermal_collector    4  solar_thermal_collector    1.0        1.0
25  10 solar_thermal_collector   10  solar_thermal_collector   10.0       10.0
26               4 geo_thermal    4              geo_thermal    1.0        1.0
27              10 geo_thermal   10              geo_thermal   10.0       10.0
28                      0 junk    0                     junk  100.0      100.0
29                     10 junk   10                     junk  100.0      100.0

## p

In [3]:
base = np.ones((3,generators_df.shape[0]))
scale = np.array([0.0,0.5,1.0])

for i in range(scale.shape[0]):
    base[i,:] = scale[i] * base[i,:]
    
base

array([[0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. ],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
        0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
        0.5, 0.5, 0.5, 0.5],
       [1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. ,
        1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. ,
        1. , 1. , 1. , 1. ]])

In [4]:
generators_df["name"]

0                      0 biomass
1                     10 biomass
2          0 central_biomass_CHP
3         10 central_biomass_CHP
4                 0 run_of_river
5                10 run_of_river
6                          0 gas
7                         10 gas
8          0 other_non_renewable
9         10 other_non_renewable
10                   0 reservoir
11                  10 reservoir
12                     0 solar_0
13                     0 solar_1
14                    10 solar_0
15                    10 solar_1
16             0 solar_rooftop_0
17             0 solar_rooftop_1
18            10 solar_rooftop_0
19            10 solar_rooftop_1
20              0 wind_onshore_0
21              0 wind_onshore_1
22             10 wind_onshore_0
23             10 wind_onshore_1
24     4 solar_thermal_collector
25    10 solar_thermal_collector
26                 4 geo_thermal
27                10 geo_thermal
28                        0 junk
29                       10 junk
Name: name

In [5]:
power_df = pd.DataFrame(base, columns=generators_df["name"].to_list())
power_df

0 biomass  10 biomass  0 central_biomass_CHP  10 central_biomass_CHP  \
0        0.0         0.0                    0.0                     0.0   
1        0.5         0.5                    0.5                     0.5   
2        1.0         1.0                    1.0                     1.0   

   0 run_of_river  10 run_of_river  0 gas  10 gas  0 other_non_renewable  \
0             0.0              0.0    0.0     0.0                    0.0   
1             0.5              0.5    0.5     0.5                    0.5   
2             1.0              1.0    1.0     1.0                    1.0   

   10 other_non_renewable  ...  0 wind_onshore_0  0 wind_onshore_1  \
0                     0.0  ...               0.0               0.0   
1                     0.5  ...               0.5               0.5   
2                     1.0  ...               1.0               1.0   

   10 wind_onshore_0  10 wind_onshore_1  4 solar_thermal_collector  \
0                0.0                0.0                        0.0   
1                0.5                0.5                        0.5   
2                1.0                1.0                        1.0   

   10 solar_thermal_collector  4 geo_thermal  10 geo_thermal  0 junk  10 junk  
0                         0.0            0.0             0.0     0.0      0.0  
1                         0.5            0.5             0.5     0.5      0.5  
2                         1.0            1.0             1.0     1.0      1.0  

[3 rows x 30 columns]

In [6]:
power_df.to_csv("etrago_test_network_1/generators-p.csv")
power_df.to_csv("etrago_test_network_1/generators-p_min_pu.csv")

## q

In [7]:
base = np.ones((3,generators_df.shape[0]))
scale = np.array([0.0,0.5,-1.0])

for i in range(scale.shape[0]):
    base[i,:] = scale[i] * base[i,:]
    
base

array([[ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
         0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
         0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,
         0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,
         0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [-1. , -1. , -1. , -1. , -1. , -1. , -1. , -1. , -1. , -1. , -1. ,
        -1. , -1. , -1. , -1. , -1. , -1. , -1. , -1. , -1. , -1. , -1. ,
        -1. , -1. , -1. , -1. , -1. , -1. , -1. , -1. ]])

In [8]:
generators_df["name"]

0                      0 biomass
1                     10 biomass
2          0 central_biomass_CHP
3         10 central_biomass_CHP
4                 0 run_of_river
5                10 run_of_river
6                          0 gas
7                         10 gas
8          0 other_non_renewable
9         10 other_non_renewable
10                   0 reservoir
11                  10 reservoir
12                     0 solar_0
13                     0 solar_1
14                    10 solar_0
15                    10 solar_1
16             0 solar_rooftop_0
17             0 solar_rooftop_1
18            10 solar_rooftop_0
19            10 solar_rooftop_1
20              0 wind_onshore_0
21              0 wind_onshore_1
22             10 wind_onshore_0
23             10 wind_onshore_1
24     4 solar_thermal_collector
25    10 solar_thermal_collector
26                 4 geo_thermal
27                10 geo_thermal
28                        0 junk
29                       10 junk
Name: name

In [9]:
power_df = pd.DataFrame(base, columns=generators_df["name"].to_list())
power_df

0 biomass  10 biomass  0 central_biomass_CHP  10 central_biomass_CHP  \
0        0.0         0.0                    0.0                     0.0   
1        0.5         0.5                    0.5                     0.5   
2       -1.0        -1.0                   -1.0                    -1.0   

   0 run_of_river  10 run_of_river  0 gas  10 gas  0 other_non_renewable  \
0             0.0              0.0    0.0     0.0                    0.0   
1             0.5              0.5    0.5     0.5                    0.5   
2            -1.0             -1.0   -1.0    -1.0                   -1.0   

   10 other_non_renewable  ...  0 wind_onshore_0  0 wind_onshore_1  \
0                     0.0  ...               0.0               0.0   
1                     0.5  ...               0.5               0.5   
2                    -1.0  ...              -1.0              -1.0   

   10 wind_onshore_0  10 wind_onshore_1  4 solar_thermal_collector  \
0                0.0                0.0                        0.0   
1                0.5                0.5                        0.5   
2               -1.0               -1.0                       -1.0   

   10 solar_thermal_collector  4 geo_thermal  10 geo_thermal  0 junk  10 junk  
0                         0.0            0.0             0.0     0.0      0.0  
1                         0.5            0.5             0.5     0.5      0.5  
2                        -1.0           -1.0            -1.0    -1.0     -1.0  

[3 rows x 30 columns]

In [10]:
power_df.to_csv("etrago_test_network_1/generators-q.csv")

## p_max_pu

In [11]:
base = np.ones((3,generators_df.shape[0]))
scale = np.array([0.5,0.75,1.0])

for i in range(scale.shape[0]):
    base[i,:] = scale[i] * base[i,:]
    
base

array([[0.5 , 0.5 , 0.5 , 0.5 , 0.5 , 0.5 , 0.5 , 0.5 , 0.5 , 0.5 , 0.5 ,
        0.5 , 0.5 , 0.5 , 0.5 , 0.5 , 0.5 , 0.5 , 0.5 , 0.5 , 0.5 , 0.5 ,
        0.5 , 0.5 , 0.5 , 0.5 , 0.5 , 0.5 , 0.5 , 0.5 ],
       [0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75,
        0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75,
        0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75],
       [1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ,
        1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ,
        1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ]])

In [12]:
power_df = pd.DataFrame(base, columns=generators_df["name"].to_list())
power_df

0 biomass  10 biomass  0 central_biomass_CHP  10 central_biomass_CHP  \
0       0.50        0.50                   0.50                    0.50   
1       0.75        0.75                   0.75                    0.75   
2       1.00        1.00                   1.00                    1.00   

   0 run_of_river  10 run_of_river  0 gas  10 gas  0 other_non_renewable  \
0            0.50             0.50   0.50    0.50                   0.50   
1            0.75             0.75   0.75    0.75                   0.75   
2            1.00             1.00   1.00    1.00                   1.00   

   10 other_non_renewable  ...  0 wind_onshore_0  0 wind_onshore_1  \
0                    0.50  ...              0.50              0.50   
1                    0.75  ...              0.75              0.75   
2                    1.00  ...              1.00              1.00   

   10 wind_onshore_0  10 wind_onshore_1  4 solar_thermal_collector  \
0               0.50               0.50                       0.50   
1               0.75               0.75                       0.75   
2               1.00               1.00                       1.00   

   10 solar_thermal_collector  4 geo_thermal  10 geo_thermal  0 junk  10 junk  
0                        0.50           0.50            0.50    0.50     0.50  
1                        0.75           0.75            0.75    0.75     0.75  
2                        1.00           1.00            1.00    1.00     1.00  

[3 rows x 30 columns]

In [13]:
power_df.to_csv("etrago_test_network_1/generators-p_max_pu.csv")

In [14]:
for carrier in generators_df["carrier"].unique():
    print(carrier)

biomass
central_biomass_CHP
run_of_river
gas
other_non_renewable
reservoir
solar
solar_rooftop
wind_onshore
solar_thermal_collector
geo_thermal
junk


# links

In [15]:
links_df = pd.read_csv("etrago_test_network_1/links.csv")
links_df

name  bus0  bus1                     carrier  p_nom_opt
0      0     1     0             central_gas_CHP        1.0
1      1    10    10             central_gas_CHP       10.0
2      2     0     3                         dsm        1.0
3      3    10    10                         dsm       10.0
4      4     0     4           central_heat_pump        1.0
5      5    10    10           central_heat_pump       10.0
6      6     0     4    central_resistive_heater        1.0
7      7    10    10    central_resistive_heater       10.0
8      8     4     5  central_heat_store_charger        1.0
9      9    10    10  central_heat_store_charger       10.0
10    10     0     6             rural_heat_pump        1.0
11    11    10    10             rural_heat_pump       10.0
12    12     6     7    rural_heat_store_charger        1.0
13    13    10    10    rural_heat_store_charger       10.0
14    14     0     3                 BEV charger        1.0
15    15    10    10                 BEV charger       10.0
16    16    10    10                        junk      100.0

In [16]:
base = np.ones((3,links_df.shape[0]))
scale = np.array([0.0,0.5,1.0])

for i in range(scale.shape[0]):
    base[i,:] = scale[i] * base[i,:]
    
base

array([[0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. ],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
        0.5, 0.5, 0.5, 0.5],
       [1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. ,
        1. , 1. , 1. , 1. ]])

In [17]:
power_df = pd.DataFrame(base, columns=links_df["name"].to_list())
power_df

0    1    2    3    4    5    6    7    8    9    10   11   12   13   14  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1  0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5   
2  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0   

    15   16  
0  0.0  0.0  
1  0.5  0.5  
2  1.0  1.0

In [18]:
power_df.to_csv("etrago_test_network_1/links-p0.csv")
power_df.to_csv("etrago_test_network_1/links-p1.csv")

# storage_units

In [19]:
storages_df = pd.read_csv("etrago_test_network_1/storage_units.csv")
storages_df

name  bus  carrier  p_nom_opt  p_nom_extendable  max_hours
0   0 battery    0  battery        1.0              True       10.0
1  10 battery   10  battery       10.0              True       10.0
2     10 junk   10     junk       10.0              True       10.0

In [20]:
base = np.ones((3,storages_df.shape[0]))
scale = np.array([0.0,0.5,1.0])

for i in range(scale.shape[0]):
    base[i,:] = scale[i] * base[i,:]
    
base

array([[0. , 0. , 0. ],
       [0.5, 0.5, 0.5],
       [1. , 1. , 1. ]])

In [21]:
power_df = pd.DataFrame(base, columns=storages_df["name"].to_list())
power_df

0 battery  10 battery  10 junk
0        0.0         0.0      0.0
1        0.5         0.5      0.5
2        1.0         1.0      1.0

In [22]:
power_df.to_csv("etrago_test_network_1/storage_units-p.csv")
power_df.to_csv("etrago_test_network_1/storage_units-q.csv")

# test

In [23]:
test_df = pd.read_csv("etrago_test_network_1/generators-p.csv", index_col=0)
test_df

0 biomass  10 biomass  0 central_biomass_CHP  10 central_biomass_CHP  \
0        0.0         0.0                    0.0                     0.0   
1        0.5         0.5                    0.5                     0.5   
2        1.0         1.0                    1.0                     1.0   

   0 run_of_river  10 run_of_river  0 gas  10 gas  0 other_non_renewable  \
0             0.0              0.0    0.0     0.0                    0.0   
1             0.5              0.5    0.5     0.5                    0.5   
2             1.0              1.0    1.0     1.0                    1.0   

   10 other_non_renewable  ...  0 wind_onshore_0  0 wind_onshore_1  \
0                     0.0  ...               0.0               0.0   
1                     0.5  ...               0.5               0.5   
2                     1.0  ...               1.0               1.0   

   10 wind_onshore_0  10 wind_onshore_1  4 solar_thermal_collector  \
0                0.0                0.0                        0.0   
1                0.5                0.5                        0.5   
2                1.0                1.0                        1.0   

   10 solar_thermal_collector  4 geo_thermal  10 geo_thermal  0 junk  10 junk  
0                         0.0            0.0             0.0     0.0      0.0  
1                         0.5            0.5             0.5     0.5      0.5  
2                         1.0            1.0             1.0     1.0      1.0  

[3 rows x 30 columns]